resolver: lts-14.15

packages:
- .

extra-deps:
- aeson-options-0.1.0
- base58-bytestring-0.1.0
- constraints-0.11
- hex-text-0.1.0.0
- pretty-terminal-0.1.0.0
- qm-interpolated-string-0.3.0.0
- show-type-0.1.1
- first-class-families-0.6.0.0@sha256:9d2a2a0092dfb8fd0e688b0b6bf71242fbc393c028b0b669d25ed387667490c2

# Morley and associated libraries
- git:
    https://gitlab.com/morley-framework/morley.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    c9c9f8b0449e81fc1e46f3786e00b2aedf2606d7 # martoon/#65-doc-collision
  subdirs:
    - .
    - prelude
    - morley-upgradeable
    - morley-ledgers
    - morley-ledgers-test
    - indigo
    - morley-nettest
- git: https://github.com/int-index/caps.git
  commit: ab4345eabd58fc6f05d3b46bea2c5acdba3ec6f8

- git:
    git@github.com:tqtezos/morley-dstoken.git
  commit:
    935ca03370ace435222eb3cd32402ee478b44d74 # 6e07d017ee81bcbc0a2e2cfbd6601c2e1b96436b # master
  subdirs:
    - .

nix:
  shell-file: shell.nix
