resolver: lts-13.22

packages:
- .
# - prelude
# - lorentz-contracts
# - indigo

extra-deps:
- aeson-options-0.1.0
- base58-bytestring-0.1.0
- hex-text-0.1.0.0
- show-type-0.1.1
- qm-interpolated-string-0.3.0.0

- git:
    https://gitlab.com/morley-framework/morley.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    bd3bf332f5c13e1514f48b9be3a563a9a5a1455d  # master
  subdirs:
    - .
    - indigo
    - lorentz-contracts
    - prelude
- git:
    git@github.com:tqtezos/morley-dstoken.git
  commit:
    74228541ad3ac927fcbbca351ef05f967704ccdc # master
  subdirs:
    - .

# asked for by stack (new morley dependencies?)
# - constraints-0.11.2@sha256:d028005d93f891b48b61ff0c82c6f868859eb728010dea3e355b0c55d0f57cf9
# - type-equality-1@sha256:aeb9c44abf5d2edf52caff114a7da565d8328fa84bbe194828e4355ea85bf5b3
# - aeson-options-0.1.0
# - base58-bytestring-0.1.0
- constraints-0.11
# - hex-text-0.1.0.0
- pretty-terminal-0.1.0.0
# - show-type-0.1.1

nix:
  shell-file: shell.nix
