resolver: lts-13.22

packages:
- .

extra-deps:
- aeson-options-0.1.0
- base58-bytestring-0.1.0
- constraints-0.11
- hex-text-0.1.0.0
- pretty-terminal-0.1.0.0
- qm-interpolated-string-0.3.0.0
- show-type-0.1.1
- first-class-families-0.6.0.0@sha256:9d2a2a0092dfb8fd0e688b0b6bf71242fbc393c028b0b669d25ed387667490c2

# Morley and associated libraries
- git:
    https://gitlab.com/morley-framework/morley.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    245a2152213c9d179759d6014972227ff0ccbf96  # master
  subdirs:
    - .
    - indigo
    - morley-upgradeable
    - morley-ledgers
    - prelude
- archive: /Users/michaelklein/Coding/morley-dstoken/morley-dstoken-6e07d017ee81bcbc0a2e2cfbd6601c2e1b96436b.tar.gz
# - git:
#     git@github.com:tqtezos/morley-dstoken.git
#   commit:
#     6e07d017ee81bcbc0a2e2cfbd6601c2e1b96436b # master
#   subdirs:
#     - .

nix:
  shell-file: shell.nix
